title: IT Caeer in HK - HKUST Career Development Sharing
author: 3dd13
email: tatonlto@gmail.com
venue: HKUST
date: 19th April 2011
description: "Talked about his 7 years IT experience: 100+ interviews, 8 formal Hong Kong and Singapore employers, some freelance and open source projects."

auto: on
pygments: true
